### PR TITLE
[#13] Update the information of the correct replica (master)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
so they were just being held wrong?

**Comment by korydraughn** [comment]
For the phymv case, I was not holding the API correctly. The tests would never catch this issue which is why I modified them to phymv a replica other than replica zero. Before this change, replica zero would always be the target.

**Comment by korydraughn** [comment]
added #

**Comment by korydraughn** [comment]
hold on merging this

**Pull request merged**
